model_name_or_path: openai/whisper-medium.en
dataset_name: stakwork/all-bitcoin-clips2
dataset_config_name: en
language: english
train_split_name: train
eval_split_name: test
model_index_name: Whisper-medium-BTC
gradient_accumulation_steps: 1
use_auth_token: true
output_dir: whisper-stakwork-crypto
max_steps: 350
per_device_train_batch_size: 32
per_device_eval_batch_size: 16
logging_steps: 10
learning_rate: 0.0000004
warmup_steps: 300
evaluation_strategy: steps
save_strategy: steps
save_steps: 25
eval_steps: 25
save_total_limit: 4
generation_max_length: 425
length_column_name: input_length
max_duration_in_seconds: 30
text_column_name: text
freeze_feature_encoder: False
report_to: all
metric_for_best_model: wer
greater_is_better: False
gradient_checkpointing: true
fp16: true
overwrite_output_dir: true
do_train: true
do_eval: true
load_best_model_at_end: true
predict_with_generate: true
do_normalize_eval: true
streaming: true
push_to_hub: true
hub_model_id: whisper-medium-BTCv4
model_dropout: 0.15
# WER 6.9%