model_name_or_path: openai/whisper-tiny
dataset_name: mozilla-foundation/common_voice_11_0
dataset_config_name: es
language: spanish
train_split_name: train+validation
eval_split_name: test
model_index_name: Whisper Small Spanish
max_steps: 500
output_dir: whisper-tiny-spanish-checkpoint
per_device_train_batch_size: 64
per_device_eval_batch_size: 32
logging_steps: 25
learning_rate: 0.0000005
warmup_steps: 10
evaluation_strategy: steps
eval_steps: 100
save_strategy: steps
save_steps: 100
generation_max_length: 225
length_column_name: input_length
max_duration_in_seconds: 30
text_column_name: sentence
freeze_feature_encoder: False
report_to: tensorboard
metric_for_best_model: wer
greater_is_better: False
load_best_model_at_end: true
gradient_checkpointing: true
fp16: true
overwrite_output_dir: true
do_train: true
do_eval: false
predict_with_generate: true
do_normalize_eval: true
streaming: true
push_to_hub: true
hub_model_id: whisper-tiny-spanish
max_train_samples: 500
max_eval_samples: 10